# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [20]:
# import numpy and pandas
import pandas as pd
import numpy as np
from scipy import stats


# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents.

In [39]:
# Your code here:
data = pd.read_csv('Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [40]:
# Your code here:

data.head()

Name                              Job Titles  \
0    AARON,  JEFFERY M                                SERGEANT   
1      AARON,  KARINA   POLICE OFFICER (ASSIGNED AS DETECTIVE)   
2  AARON,  KIMBERLEI R                CHIEF CONTRACT EXPEDITER   
3  ABAD JR,  VICENTE M                       CIVIL ENGINEER IV   
4    ABASCAL,  REECE E             TRAFFIC CONTROL AIDE-HOURLY   

         Department Full or Part-Time Salary or Hourly  Typical Hours  \
0            POLICE                 F           Salary            NaN   
1            POLICE                 F           Salary            NaN   
2  GENERAL SERVICES                 F           Salary            NaN   
3       WATER MGMNT                 F           Salary            NaN   
4              OEMC                 P           Hourly           20.0   

   Annual Salary  Hourly Rate  
0       101442.0          NaN  
1        94122.0          NaN  
2       101592.0          NaN  
3       110064.0          NaN  
4            NaN        19.86

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [41]:
# Your code here:

[data[i].isnull().sum() for i in data.columns]

[0, 0, 0, 0, 0, 25161, 8022, 25161]

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [42]:
# Your code here:
sal = sum(np.where(data['Salary or Hourly'] == 'Salary', 1, 0))
hourly = sum(np.where(data['Salary or Hourly'] == 'Hourly', 1, 0))
sal + hourly == len(data['Name'])

True

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [59]:
# Your code here:
dep = data.groupby(by='Department').count()

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [44]:
# Your code here:
from scipy.stats import ttest_1samp, ttest_rel, ttest_ind
from scipy.stats import f_oneway
hour = data[data['Hourly Rate'].notnull()]['Hourly Rate']
ttest_1samp(hour,30)

Ttest_1sampResult(statistic=20.6198057854942, pvalue=4.3230240486229894e-92)

We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [45]:
# Your code here:
annual = data[data['Annual Salary'].notnull()]['Annual Salary']
ttest_1samp(annual, 86000)

Ttest_1sampResult(statistic=5.932870515690814, pvalue=3.015758519916386e-09)

Using the `crosstab` function, find the department that has the most hourly workers. 

In [94]:
# Your code here:
dt = data[['Salary or Hourly', 'Department']]
ctab = pd.crosstab(dt['Department'], dt['Salary or Hourly'])
stacked = ctab.sort_values(by='Hourly',ascending=False).stack()
stacked.index[0], stacked[0]

(('STREETS & SAN', 'Hourly'), 1862)

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [102]:
# Your code here:
dept = data[data['Department'] == stacked.index[0][0]]
dept = dept[dept['Hourly Rate'].notnull()]
ttest_1samp(dept['Hourly Rate'], 35)


Ttest_1sampResult(statistic=-9.567447887848152, pvalue=3.3378530564707717e-21)

# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [112]:
# Your code here:
stats.t.interval(0.95, hour, loc=np.mean(hour), scale=stats.sem(hour, ddof=len(hour)-1))


(array([7.51232632, 8.41016026, 8.21506596, ..., 8.21506596, 8.41370022,
        8.44705823]),
 array([58.06478911, 57.16695518, 57.36204948, ..., 57.36204948,
        57.16341521, 57.13005721]))

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [110]:
# Your code here:

stats.t.interval(0.95, annual, loc=np.mean(annual), scale=stats.sem(annual, ddof=len(annual)-1))

(array([45547.0300629 , 45546.99179434, 45547.03078943, ...,
        45546.9676529 , 45546.98743141, 45547.09156447]),
 array([128026.96951741, 128027.00778597, 128026.96879088, ...,
        128027.03192741, 128027.01214889, 128026.90801584]))

# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [120]:
# Your code here:
import statsmodels

proportions_ztest()


AttributeError: module 'scipy.stats' has no attribute 'proportions_ztest'